from __future__ import annotations

import json
import re
import unicodedata
from pathlib import Path
from typing import Any

from PIL import Image, ImageDraw, ImageFont

from .fetch import get_music_lookup
from .music_catalog import song_id

DESIGN_CREDIT = (
    "Designed by Yuri-YuzuChaN & BlueDeer233 | Generated by AstrBot"
)
DIFFICULTIES = ("Basic", "Advanced", "Expert", "Master", "Re:Master")
CARD_ASSETS = (
    "b50_score_basic.png",
    "b50_score_advanced.png",
    "b50_score_expert.png",
    "b50_score_master.png",
    "b50_score_remaster.png",
)
THEME_EXACT_FILES = {
    "b50.png",
    "b50_bg.png",
    "logo.png",
    "chart_info.png",
    "play_info.png",
    "ra_dx.png",
    "ra.png",
    "ra-dx.png",
    "song_bg.png",
    "info_bg.png",
}
THEME_PREFIXES = (
    "UI_TTR_Rank_",
    "UI_CMN_DXRating_",
    "UI_CMN_DXRating_Star_",
)
RANK_MAP = {
    "d": "D",
    "c": "C",
    "b": "B",
    "bb": "BB",
    "bbb": "BBB",
    "a": "A",
    "aa": "AA",
    "aaa": "AAA",
    "s": "S",
    "sp": "Sp",
    "ss": "SS",
    "ssp": "SSp",
    "sss": "SSS",
    "sssp": "SSSp",
}
FC_MAP = {
    "fc": "FC",
    "fcp": "FCp",
    "fc+": "FCp",
    "ap": "AP",
    "app": "APp",
    "ap+": "APp",
}
FS_MAP = {
    "fs": "FS",
    "fsp": "FSp",
    "fs+": "FSp",
    "fsd": "FSD",
    "fdx": "FSD",
    "fsdp": "FSDp",
    "fdxp": "FSDp",
    "fdx+": "FSDp",
    "sync": "Sync",
}
ID_COLORS = (
    (129, 217, 85),
    (245, 189, 21),
    (255, 129, 141),
    (159, 81, 220),
    (138, 0, 226),
)


def _f(value: Any, default: float = 0.0) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def _i(value: Any, default: int = 0) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


def _pic_dir(assets: Path) -> Path:
    return assets / "mai" / "pic"


def _theme_path(assets: Path, filename: str) -> Path:
    pic = _pic_dir(assets)
    mapped = "b50.png" if filename == "b50_bg.png" else filename
    themed = filename in THEME_EXACT_FILES or filename.startswith(THEME_PREFIXES)
    candidates = (
        (
            pic / "prism_plus" / mapped,
            pic / "circle" / mapped,
            pic / filename,
            pic / mapped,
        )
        if themed
        else (
            pic / filename,
            pic / mapped,
            pic / "prism_plus" / mapped,
            pic / "circle" / mapped,
        )
    )
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return candidates[0]


def _font_path(assets: Path, torus: bool = False) -> Path:
    font = assets / "font"
    names = (
        ("Torus SemiBold.otf", "ResourceHanRoundedCN-Bold.ttf")
        if torus
        else ("ResourceHanRoundedCN-Bold.ttf", "ResourceHanRoundedCN.otf")
    )
    for name in names:
        path = font / name
        if path.exists():
            return path
    return font / names[0]


def missing_assets(assets_path: str | Path) -> list[str]:
    assets = Path(assets_path)
    required = [
        _theme_path(assets, "b50_bg.png"),
        _font_path(assets),
        _font_path(assets, torus=True),
        *(_theme_path(assets, name) for name in CARD_ASSETS),
    ]
    return [str(path.relative_to(assets)) for path in required if not path.is_file()]


def valid_assets(assets_path: str | Path) -> bool:
    return not missing_assets(assets_path)


def _open(path: Path, size: tuple[int, int] | None = None) -> Image.Image:
    with Image.open(path) as source:
        image = source.convert("RGBA")
    if size:
        image = image.resize(size, Image.Resampling.LANCZOS)
    return image


def _optional(
    assets: Path, filename: str, size: tuple[int, int] | None = None
) -> Image.Image | None:
    path = _theme_path(assets, filename)
    if not path.exists():
        path = _pic_dir(assets) / filename
    return _open(path, size) if path.exists() else None


def _paste_optional(
    base: Image.Image, image: Image.Image | None, xy: tuple[int, int]
) -> None:
    if image is not None:
        base.alpha_composite(image, xy)


def _display_width(text: str) -> int:
    return sum(
        2 if unicodedata.east_asian_width(char) in {"W", "F", "A"} else 1
        for char in text
    )


def _truncate(text: object, width: int) -> str:
    value = str(text or "")
    if _display_width(value) <= width:
        return value
    result = ""
    for char in value:
        if _display_width(result + char) > width - 3:
            break
        result += char
    return result + "..."


def _rank_name(chart: dict) -> str:
    rate = str(chart.get("rate") or "").strip()
    if rate:
        return RANK_MAP.get(rate.casefold(), rate)
    achievement = _f(chart.get("achievement") or chart.get("achievements"))
    for threshold, name in (
        (100.5, "SSSp"),
        (100.0, "SSS"),
        (99.5, "SSp"),
        (99.0, "SS"),
        (98.0, "Sp"),
        (97.0, "S"),
        (94.0, "AAA"),
        (90.0, "AA"),
        (80.0, "A"),
        (75.0, "BBB"),
        (70.0, "BB"),
        (60.0, "B"),
        (50.0, "C"),
    ):
        if achievement >= threshold:
            return name
    return "D"


def _rating_asset(rating: int) -> str:
    thresholds = (
        (1000, "01"),
        (2000, "02"),
        (4000, "03"),
        (7000, "04"),
        (10000, "05"),
        (12000, "06"),
        (13000, "07"),
        (14000, "08"),
        (14500, "09"),
        (15000, "10"),
    )
    for threshold, number in thresholds:
        if rating < threshold:
            return f"UI_CMN_DXRating_{number}.png"
    return "UI_CMN_DXRating_11.png"


def _cover_path(assets: Path, sid: str) -> Path | None:
    try:
        base = str(int(sid) % 10000)
    except ValueError:
        base = sid.lstrip("0") or "0"
    names = (sid, base, base.zfill(4), base.zfill(5), "0")
    for cover_dir in (assets / "mai" / "cover", assets / "cover"):
        for name in names:
            for suffix in (".png", ".jpg", ".jpeg"):
                candidate = cover_dir / f"{name}{suffix}"
                if candidate.exists():
                    return candidate
    return None


def _placeholder_cover(size: tuple[int, int]) -> Image.Image:
    image = Image.new("RGBA", size, (228, 232, 239, 255))
    draw = ImageDraw.Draw(image)
    draw.rectangle((4, 4, size[0] - 5, size[1] - 5), outline=(160, 168, 180), width=2)
    return image


def _music_lookup(context: dict) -> dict[str, dict]:
    local = context.get("music_data")
    if isinstance(local, list):
        lookup = {
            str(item.get("id")): item
            for item in local
            if isinstance(item, dict) and item.get("id") is not None
        }
        if lookup:
            return lookup
    return get_music_lookup() or {}


def _max_dx_score(chart: dict, lookup: dict[str, dict]) -> int:
    music = lookup.get(str(chart.get("music_id") or chart.get("song_id") or ""))
    index = _i(chart.get("level_index"), -1)
    charts = (music or {}).get("charts") or []
    if not 0 <= index < len(charts):
        return 0
    notes = charts[index].get("notes") or []
    return sum(_i(note) for note in notes) * 3


def _dx_star(score: int, maximum: int) -> int:
    if maximum <= 0:
        return 0
    percentage = score / maximum * 100
    if percentage < 85:
        return 0
    if percentage < 90:
        return 1
    if percentage < 93:
        return 2
    if percentage < 95:
        return 3
    if percentage < 97:
        return 4
    return 5


class AWMCRenderer:
    def __init__(self, context: dict, assets_path: str) -> None:
        self.context = context
        self.assets = Path(assets_path)
        missing = missing_assets(self.assets)
        if missing:
            raise RuntimeError("AWMC 素材不完整，缺少：" + "、".join(missing))
        self.image = _open(_theme_path(self.assets, "b50_bg.png"))
        if self.image.size != (1400, 1600):
            self.image = self.image.resize((1400, 1600), Image.Resampling.LANCZOS)
        self.draw = ImageDraw.Draw(self.image)
        self.cn_fonts: dict[int, ImageFont.FreeTypeFont] = {}
        self.torus_fonts: dict[int, ImageFont.FreeTypeFont] = {}
        self.cards = [_open(_theme_path(self.assets, name)) for name in CARD_ASSETS]
        self.lookup = _music_lookup(context)

    def font(self, size: int, torus: bool = False) -> ImageFont.FreeTypeFont:
        cache = self.torus_fonts if torus else self.cn_fonts
        if size not in cache:
            cache[size] = ImageFont.truetype(str(_font_path(self.assets, torus)), size)
        return cache[size]

    def text(
        self,
        xy: tuple[int, int],
        text: object,
        size: int,
        fill: Any,
        anchor: str = "la",
        *,
        torus: bool = False,
        stroke: int = 0,
        stroke_fill: Any = None,
    ) -> None:
        self.draw.text(
            xy,
            str(text),
            font=self.font(size, torus),
            fill=fill,
            anchor=anchor,
            stroke_width=stroke,
            stroke_fill=stroke_fill,
        )

    def _header(self) -> None:
        player = self.context.get("player") or {}
        rating = _i(player.get("rating"))
        _paste_optional(
            self.image, _optional(self.assets, "logo.png", (249, 120)), (14, 60)
        )

        plate_name = Path(str(player.get("plate") or "")).name
        plate_paths = (
            [
                self.assets / "mai" / "plate" / plate_name,
                _pic_dir(self.assets) / plate_name,
                _theme_path(self.assets, "UI_Plate_550101.png"),
            ]
            if plate_name
            else [_theme_path(self.assets, "UI_Plate_550101.png")]
        )
        plate_path = next((path for path in plate_paths if path.is_file()), None)
        if plate_path:
            self.image.alpha_composite(_open(plate_path, (800, 130)), (300, 60))

        _paste_optional(
            self.image,
            _optional(self.assets, "UI_Icon_509506.png", (120, 120)),
            (305, 65),
        )
        qq = str(player.get("qq") or "")
        avatar = self.assets / "avatars" / f"{qq}.png"
        if qq and avatar.exists():
            try:
                self.image.alpha_composite(_open(avatar, (120, 120)), (305, 65))
            except OSError:
                pass

        _paste_optional(
            self.image,
            _optional(self.assets, _rating_asset(rating), (186, 35)),
            (435, 72),
        )
        digits_ok = True
        digits: list[Image.Image] = []
        for digit in f"{rating:05d}":
            image = _optional(self.assets, f"UI_NUM_Drating_{digit}.png", (17, 20))
            if image is None:
                digits_ok = False
                break
            digits.append(image)
        if digits_ok:
            for index, image in enumerate(digits):
                self.image.alpha_composite(image, (520 + 15 * index, 80))
        else:
            self.text(
                (520, 80),
                f"{rating:05d}",
                19,
                "white",
                torus=True,
                stroke=2,
                stroke_fill="#39405a",
            )

        _paste_optional(self.image, _optional(self.assets, "Name.png"), (435, 115))
        course = _i(player.get("additional_rating"))
        course_number = course if course <= 10 else course + 1
        _paste_optional(
            self.image,
            _optional(
                self.assets, f"UI_DNM_DaniPlate_{course_number:02d}.png", (80, 32)
            ),
            (625, 120),
        )
        _paste_optional(
            self.image,
            _optional(self.assets, "UI_FBR_Class_00.png", (90, 54)),
            (620, 60),
        )
        _paste_optional(
            self.image,
            _optional(self.assets, "UI_CMN_Shougou_Rainbow.png", (270, 27)),
            (435, 160),
        )

        self.text((445, 135), _truncate(player.get("nickname"), 22), 25, "black", "lm")
        summary = self.context.get("summary") or {}
        b35 = _i(summary.get("b35_ra"))
        b15 = _i(summary.get("b15_ra"))
        self.text(
            (570, 172),
            f"B35: {b35} + B15: {b15} = {rating}",
            17,
            "black",
            "mm",
            stroke=3,
            stroke_fill="white",
        )
        source = str(player.get("source") or "")
        if source:
            self.text(
                (570, 198),
                f"数据源：{source}",
                14,
                (70, 70, 70),
                "mm",
                stroke=2,
                stroke_fill=(255, 255, 255, 220),
            )
        self.text(
            (700, 1570),
            DESIGN_CREDIT,
            23,
            (124, 129, 255),
            "mm",
            stroke=4,
            stroke_fill="white",
        )

    def _card(self, chart: dict, x: int, y: int) -> None:
        index = max(0, min(_i(chart.get("level_index"), 3), 4))
        self.image.alpha_composite(self.cards[index], (x, y))
        sid = str(chart.get("music_id") or chart.get("song_id") or "")
        cover_path = _cover_path(self.assets, sid)
        cover = (
            _open(cover_path, (75, 75)) if cover_path else _placeholder_cover((75, 75))
        )
        self.image.alpha_composite(cover, (x + 12, y + 12))

        kind = str(chart.get("type") or "SD").upper()
        _paste_optional(
            self.image,
            _optional(self.assets, f"{kind}.png", (37, 14)),
            (x + 51, y + 91),
        )
        rank = _optional(self.assets, f"UI_TTR_Rank_{_rank_name(chart)}.png", (63, 28))
        _paste_optional(self.image, rank, (x + 92, y + 78))

        fc_key = FC_MAP.get(str(chart.get("fc") or "").casefold())
        if fc_key:
            _paste_optional(
                self.image,
                _optional(self.assets, f"UI_MSS_MBase_Icon_{fc_key}.png", (34, 34)),
                (x + 154, y + 77),
            )
        fs_key = FS_MAP.get(str(chart.get("fs") or "").casefold())
        if fs_key:
            _paste_optional(
                self.image,
                _optional(self.assets, f"UI_MSS_MBase_Icon_{fs_key}.png", (34, 34)),
                (x + 185, y + 77),
            )

        maximum = _max_dx_score(chart, self.lookup)
        dx_score = _i(chart.get("dxScore") or chart.get("dx_score"))
        star = _dx_star(dx_score, maximum)
        if star:
            _paste_optional(
                self.image,
                _optional(
                    self.assets, f"UI_GAM_Gauge_DXScoreIcon_0{star}.png", (47, 26)
                ),
                (x + 217, y + 80),
            )

        color = "white"
        self.text((x + 26, y + 98), sid, 13, ID_COLORS[index], "mm", torus=True)
        self.text((x + 93, y + 14), _truncate(chart.get("title"), 18), 14, color, "lm")
        achievement = _f(chart.get("achievement") or chart.get("achievements"))
        self.text((x + 93, y + 38), f"{achievement:.4f}%", 30, color, "lm", torus=True)
        self.text(
            (x + 93, y + 65),
            f"{_f(chart.get('ds')):.1f} -> {_i(chart.get('ra'))}",
            15,
            color,
            "lm",
            torus=True,
        )
        self.text(
            (x + 219, y + 65), f"{dx_score}/{maximum}", 15, color, "mm", torus=True
        )

    def render(self) -> Image.Image:
        self._header()
        charts = [
            item for item in (self.context.get("b50") or []) if isinstance(item, dict)
        ]
        b35 = [item for item in charts if item.get("bucket") == "B35"][:35]
        b15 = [item for item in charts if item.get("bucket") == "B15"][:15]
        if not b35 and not b15:
            b35, b15 = charts[:35], charts[35:50]
        for start_y, group in ((235, b35), (1085, b15)):
            for number, chart in enumerate(group):
                x = 16 + 276 * (number % 5)
                y = start_y + 114 * (number // 5)
                self._card(chart, x, y)
        return self.image.convert("RGB")


def render_b50(context: dict, assets_path: str) -> Image.Image:
    return AWMCRenderer(context, assets_path).render()


def _parse_analysis(raw: str) -> dict:
    text = re.sub(
        r"^```(?:json)?\s*|\s*```$", "", str(raw or "").strip(), flags=re.IGNORECASE
    )
    try:
        value = json.loads(text)
    except json.JSONDecodeError:
        match = re.search(r"\{[\s\S]*\}", text)
        try:
            value = json.loads(match.group(0)) if match else {}
        except json.JSONDecodeError:
            value = {}
    structured = isinstance(value, dict)
    if not structured:
        value = {}

    def scalar(field: str, *aliases: str) -> str:
        for key in (field, *aliases):
            item = value.get(key)
            if isinstance(item, str) and item.strip():
                return item.strip()
            if isinstance(item, dict):
                for nested_key in ("text", "content", "value", field):
                    nested = item.get(nested_key)
                    if isinstance(nested, str) and nested.strip():
                        return nested.strip()
        return ""

    title = scalar("title") or "B50 锐评"
    overall = scalar(
        "overall_roast", "overall", "roast", "commentary", "content", "analysis"
    )
    if overall and (
        overall.lstrip().startswith("{")
        or any(
            f'"{key}"' in overall
            for key in ("title", "overall_roast", "push_recommendations")
        )
    ):
        try:
            nested = json.loads(overall)
        except json.JSONDecodeError:
            nested = None
        if isinstance(nested, dict):
            nested_overall = nested.get("overall_roast")
            overall = (
                nested_overall.strip()
                if isinstance(nested_overall, str) and nested_overall.strip()
                else ""
            )
        else:
            overall = ""
    if not overall:
        looks_structured = structured or text.lstrip().startswith("{") or any(
            f'"{key}"' in text
            for key in ("title", "overall_roast", "push_recommendations")
        )
        overall = (
            "模型输出格式异常，本次未能生成可读锐评，请重新尝试。"
            if looks_structured
            else text
        )
    return {
        "title": _plain_analysis_text(title),
        "overall": _plain_analysis_text(overall),
        "impression": _plain_analysis_text(scalar("impression_roast")),
        "recommendations": value.get("push_recommendations")
        if isinstance(value.get("push_recommendations"), list)
        else [],
    }


_REMOVED_FORMAT_TAG = re.compile(r"<\s*/?\s*r\s*>", re.IGNORECASE)


def _plain_analysis_text(text: str) -> str:
    return _REMOVED_FORMAT_TAG.sub("", str(text or ""))


def _wrap_analysis_text(
    draw: ImageDraw.ImageDraw, text: str, font: ImageFont.FreeTypeFont, width: int
) -> list[str]:
    lines: list[str] = []
    current = ""
    for char in _plain_analysis_text(text):
        if char == "\r":
            continue
        if char == "\n":
            lines.append(current)
            current = ""
            continue
        if current and draw.textlength(current + char, font=font) > width:
            lines.append(current)
            current = ""
        current += char
    lines.append(current)
    return lines or [""]


def render_analysis(context: dict, analysis_text: str, assets_path: str) -> Image.Image:
    b50 = render_b50(context, assets_path).convert("RGBA")
    parsed = _parse_analysis(analysis_text)
    assets = Path(assets_path)
    title_font = ImageFont.truetype(str(_font_path(assets)), 42)
    body_font = ImageFont.truetype(str(_font_path(assets)), 27)
    small_font = ImageFont.truetype(str(_font_path(assets)), 23)
    probe = ImageDraw.Draw(b50)
    body_lines = _wrap_analysis_text(probe, parsed["overall"], body_font, 1230)
    impression_lines = (
        _wrap_analysis_text(probe, parsed["impression"], body_font, 1230)
        if parsed["impression"]
        else []
    )
    recommendation_lines: list[str] = []
    for index, item in enumerate(parsed["recommendations"][:3], 1):
        if not isinstance(item, dict):
            continue
        title = item.get("title") or item.get("song_title") or "候选谱面"
        detail = item.get("reason") or item.get("comment") or ""
        recommendation_lines.extend(
            _wrap_analysis_text(probe, f"{index}. {title}  {detail}", small_font, 1200)
        )
    panel_height = (
        280
        + 40 * len(body_lines)
        + 40 * len(impression_lines)
        + 34 * len(recommendation_lines)
    )
    panel_height = max(panel_height, 420)
    output = Image.new("RGBA", (1400, 1600 + panel_height), (235, 243, 255, 255))
    output.alpha_composite(b50, (0, 0))
    draw = ImageDraw.Draw(output)
    draw.rounded_rectangle(
        (45, 1635, 1355, 1600 + panel_height - 45),
        radius=32,
        fill=(255, 255, 255, 242),
        outline=(124, 129, 255, 255),
        width=5,
    )
    draw.text(
        (80, 1680), parsed["title"], font=title_font, fill=(73, 75, 145), anchor="la"
    )
    y = 1750
    for line in body_lines:
        draw.text((85, y), line, font=body_font, fill=(35, 39, 52), anchor="la")
        y += 40
    if impression_lines:
        y += 12
        for line in impression_lines:
            draw.text((85, y), line, font=body_font, fill=(65, 70, 92), anchor="la")
            y += 40
    if recommendation_lines:
        y += 18
        draw.text(
            (85, y),
            "最值得继续折腾的成绩",
            font=body_font,
            fill=(73, 75, 145),
            anchor="la",
        )
        y += 42
        for line in recommendation_lines:
            draw.text((105, y), line, font=small_font, fill=(45, 49, 65), anchor="la")
            y += 34
    return output.convert("RGB")


def render_song_info(song: dict, assets_path: str) -> Image.Image:
    assets = Path(assets_path)
    pic = _pic_dir(assets)
    template = _theme_path(assets, "chart_info.png")
    if template.exists():
        image = _open(template)
    else:
        image = Image.new("RGBA", (1200, 1300), (239, 246, 255, 255))
    if image.size != (1200, 1300):
        image = image.resize((1200, 1300), Image.Resampling.LANCZOS)
    draw = ImageDraw.Draw(image)
    cn = lambda size: ImageFont.truetype(str(_font_path(assets)), size)
    torus = lambda size: ImageFont.truetype(str(_font_path(assets, torus=True)), size)
    color = (124, 129, 255)

    _paste_optional(image, _optional(assets, "logo.png", (249, 120)), (65, 25))
    info = song.get("basic_info") or {}
    if info.get("is_new"):
        _paste_optional(
            image,
            _optional(assets, "UI_CMN_TabTitle_NewSong.png", (249, 120)),
            (842, 100),
        )
    sid = song_id(song)
    cover_path = _cover_path(assets, sid)
    cover = (
        _open(cover_path, (242, 242)) if cover_path else _placeholder_cover((242, 242))
    )
    image.alpha_composite(cover, (133, 197))
    version = str(info.get("from") or info.get("version") or "")
    if version and (pic / f"{version}.png").exists():
        image.alpha_composite(_open(pic / f"{version}.png", (182, 90)), (800, 370))
    kind = str(song.get("type") or "SD").upper()
    _paste_optional(image, _optional(assets, f"{kind}.png", (80, 30)), (295, 410))

    draw.text(
        (405, 220),
        _truncate(song.get("title"), 40),
        font=cn(28),
        fill=color,
        anchor="lm",
    )
    draw.text(
        (407, 265),
        _truncate(info.get("artist"), 50),
        font=cn(20),
        fill=color,
        anchor="lm",
    )
    draw.text(
        (460, 345), str(info.get("bpm") or "-"), font=torus(24), fill=color, anchor="lm"
    )
    draw.text((405, 435), f"ID {sid}", font=torus(22), fill=color, anchor="lm")
    draw.text(
        (665, 435), str(info.get("genre") or "-"), font=cn(24), fill=color, anchor="mm"
    )

    levels = song.get("level") or []
    constants = song.get("ds") or []
    charts = song.get("charts") or []
    for index, chart in enumerate(charts[:5]):
        y = 590 + 70 * index
        level = levels[index] if index < len(levels) else "-"
        constant = constants[index] if index < len(constants) else "-"
        draw.text(
            (120, y), f"{level}({constant})", font=torus(21), fill="white", anchor="mm"
        )
        charter = chart.get("charter") or "-"
        draw.text(
            (310, y), _truncate(charter, 19), font=cn(19), fill=color, anchor="mm"
        )
        notes = [_i(value) for value in (chart.get("notes") or [])]
        values: list[Any] = [sum(notes), *notes]
        if len(notes) == 4:
            values.insert(4, "-")
        for column in range(6):
            value = values[column] if column < len(values) else "-"
            draw.text(
                (480 + 122 * column, y),
                str(value),
                font=torus(23),
                fill=color,
                anchor="mm",
            )

    draw.text(
        (600, 1220),
        DESIGN_CREDIT,
        font=cn(22),
        fill=color,
        anchor="mm",
        stroke_width=3,
        stroke_fill="white",
    )
    return image.convert("RGB")


def render_play_info(
    song: dict,
    records: list[dict],
    assets_path: str,
    source_label: str,
) -> Image.Image:
    """Render the upstream AWMC personal per-song score page."""
    assets = Path(assets_path)
    pic = _pic_dir(assets)
    template = _theme_path(assets, "play_info.png")
    image = (
        _open(template)
        if template.exists()
        else Image.new("RGBA", (1200, 900), (239, 246, 255, 255))
    )
    draw = ImageDraw.Draw(image)
    cn = lambda size: ImageFont.truetype(str(_font_path(assets)), size)
    torus = lambda size: ImageFont.truetype(str(_font_path(assets, torus=True)), size)
    color = (124, 129, 255)
    sid = song_id(song)
    basic = song.get("basic_info") or {}

    _paste_optional(image, _optional(assets, "logo.png", (249, 120)), (42, 34))
    cover_path = _cover_path(assets, sid)
    cover = (
        _open(cover_path, (300, 300)) if cover_path else _placeholder_cover((300, 300))
    )
    image.alpha_composite(cover, (100, 260))
    version = str(basic.get("from") or basic.get("version") or "")
    if version and (pic / f"{version}.png").exists():
        image.alpha_composite(_open(pic / f"{version}.png", (183, 90)), (295, 205))
    kind = str(song.get("type") or "SD").upper()
    _paste_optional(image, _optional(assets, f"{kind}.png", (55, 20)), (350, 560))

    draw.text(
        (255, 595),
        _truncate(basic.get("artist"), 58),
        font=cn(12),
        fill=color,
        anchor="mm",
    )
    draw.text(
        (255, 622),
        _truncate(song.get("title"), 38),
        font=cn(18),
        fill=color,
        anchor="mm",
    )
    draw.text((160, 720), sid, font=torus(22), fill=color, anchor="mm")
    draw.text(
        (380, 720),
        str(basic.get("bpm") or "-"),
        font=torus(22),
        fill=color,
        anchor="mm",
    )
    draw.text(
        (1120, 70),
        f"数据源：{source_label}",
        font=cn(18),
        fill=color,
        anchor="rm",
        stroke_width=2,
        stroke_fill="white",
    )

    levels = song.get("level") or []
    constants = song.get("ds") or []
    music_charts = song.get("charts") or []
    by_level = {
        _i(record.get("level_index"), -1): record
        for record in records
        if isinstance(record, dict)
    }
    lookup = {sid: song}
    row_count = min(max(len(levels), len(music_charts), 4), 5)
    for index in range(row_count):
        row_y = 235 + 100 * index
        _paste_optional(image, _optional(assets, f"d_{index}.png"), (650, row_y))
        ds = _f(constants[index]) if index < len(constants) else 0.0
        draw.text(
            (685, 248 + 100 * index),
            f"{ds:.1f}",
            font=torus(20),
            fill=color,
            anchor="mm",
        )
        record = by_level.get(index)
        if not record:
            draw.text(
                (800, 302 + 100 * index),
                "未游玩",
                font=cn(30),
                fill=color,
                anchor="mm",
            )
            continue

        _paste_optional(
            image,
            _optional(assets, "ra_dx.png", (102, 44)),
            (850, 272 + 100 * index),
        )
        rank = _optional(
            assets,
            f"UI_TTR_Rank_{_rank_name(record)}.png",
            (100, 45),
        )
        _paste_optional(image, rank, (737, 272 + 100 * index))
        _paste_optional(
            image,
            _optional(assets, "fcfs.png"),
            (965, 265 + 100 * index),
        )

        fc_key = FC_MAP.get(str(record.get("fc") or "").casefold())
        if fc_key:
            fc = _optional(assets, f"UI_CHR_PlayBonus_{fc_key}.png", (65, 65))
            if fc is None:
                fc = _optional(assets, f"UI_MSS_MBase_Icon_{fc_key}.png", (55, 55))
            _paste_optional(image, fc, (960, 261 + 100 * index))
        fs_key = FS_MAP.get(str(record.get("fs") or "").casefold())
        if fs_key:
            fs = _optional(assets, f"UI_CHR_PlayBonus_{fs_key}.png", (65, 65))
            if fs is None:
                fs = _optional(assets, f"UI_MSS_MBase_Icon_{fs_key}.png", (55, 55))
            _paste_optional(image, fs, (1025, 261 + 100 * index))

        maximum = _max_dx_score(record, lookup)
        dx_score = _i(record.get("dxScore") or record.get("dx_score"))
        star = _dx_star(dx_score, maximum)
        if star:
            _paste_optional(
                image,
                _optional(
                    assets,
                    f"UI_GAM_Gauge_DXScoreIcon_0{star}.png",
                    (32, 19),
                ),
                (851, 296 + 100 * index),
            )
        draw.text(
            (916, 304 + 100 * index),
            f"{dx_score}/{maximum}",
            font=torus(13),
            fill=color,
            anchor="mm",
        )
        achievement = _f(record.get("achievement") or record.get("achievements"))
        draw.text(
            (500, 295 + 100 * index),
            f"{achievement:.4f}%",
            font=torus(30),
            fill=color,
            anchor="lm",
        )
        draw.text(
            (915, 283 + 100 * index),
            str(_i(record.get("ra"))),
            font=torus(18),
            fill=color,
            anchor="mm",
        )

    footer_size = 18
    while (
        footer_size > 10
        and draw.textlength(DESIGN_CREDIT, font=cn(footer_size)) > image.width - 80
    ):
        footer_size -= 1
    draw.text(
        (image.width // 2, image.height - 22),
        DESIGN_CREDIT,
        font=cn(footer_size),
        fill=color,
        anchor="mm",
        stroke_width=3,
        stroke_fill="white",
    )
    return image.convert("RGB")
